config/routes.rb
Rails.application.routes.draw do

  resources :photos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photos = Photo.all
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)
    @photo.save

    redirect_to photos_url
  end

  def show
    @photo = Photo.find(params[:id])
  end
   
  private

  def photo_params
    params.require(:photo).permit(:title, :date, :description, :file_location)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoAlbum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/photos/index.html.erb
<ul>
  <% @photos.each do |photo| %>
    <li>
      <%= photo.title %>
      <%= link_to 'Show', photo_path(photo) %>
      <%= link_to 'Edit', edit_photo_path(photo) %>
      <%= link_to 'Destroy', photo_path(photo), method: :delete, data:{ confirm: "Are you sure?" } %>
    </li>
  <% end %>
</ul>

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<%= form_for @photo, :url => photos_path do |f| %>
  <%= f.label :title, "Title" %>
  <%= f.text_field :title %>

  <%= f.label :date, "Date" %>
  <%= f.text_field :date %>

  <%= f.label :description, "Description" %>
  <%= f.text_area :description %>

  <%= f.label :file_location, "File Location" %>
  <%= f.text_field :file_location %>

  <%= f.submit "Create" %>
<% end %>

app/views/photos/show.html.erb
<%= @photo.title %>
<%= @photo.date %>
<img src=<%= "/"+@photo.file_location %> /> 
<%= simple_format(@photo.description) %>
<%= link_to 'Back to index', photos_path %>